### ISSUE TITLE
Autocomplete Issues

### ISSUE THREAD

**Issue by prasanna1211** [Codebrahma/react-lite-ui#1]
1. The default input height is small
2. on hover of dropdown should be pointer
3. Default font size should be increased
4. Pressing `ENTER` key should select the first option on the drop-down shown. If no option available on dropdown, then it should do nothing.
6. Props can be modified like:
    - data - array of objects
    - labelKey - keyname in every object to refer for label
    - valueKey - keyname in every object to refer for the value

**Comment by prasanna1211** [comment]
Height of the input display in Autocomplete is small
Pressing Tab automatically selects the first option. The behaviour to select should be only when we press enter and on tab it should clear the input display

**Comment by rishichawda** [comment]
@prasanna1211 Please check if this is the desired behaviour and merge the pull request.
