### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by prasanna1211** [Codebrahma/react-lite-ui#10]
1. Documentation is missing for the following components.
a. Avatar
b. Checkbox
c. Checkbox Group
d. Multi Select
e. Navbar
f. Radio Button Group
g. select
h. Snackbar
i. Toggle
j. Tooltip

**Comment by KRRISH96** [comment]
Docs added for all missing components. Ref tagged PR's.

| Component     | PR|
|:---------|:-----------|
| `a. Avatar`   | #32 |
| `b. Checkbox`   | #45 |
| `c. Checkbox Group`   | #47 |
| `d. Multi Select`   | #40 |
| `e. Navbar`   | #53 |
| `f. RadioButton Group`   | #51 |
| `g. Select`   | #44 |
| `h. Snackbar`   | #48 |
| `i. Toggle`   | #41 |
| `j. Tooltip`   | #33 |
