### ISSUE TITLE
Clicking on `CB React-Lite-UI` logo should take the user to '/'

### ISSUE THREAD

**Issue by Kameshwaran** [Codebrahma/react-lite-ui#12]
<img width="1280" alt="screen shot 2018-09-28 at 11 02 46 am" src="https://user-images.githubusercontent.com/5488330/46189792-1095a080-c30e-11e8-8d0c-cb50876740c1.png">
Clicking on the `Logo` should take the user to '/' irrespective of whatever the page they are in.

**Comment by prasanna1211** [comment]
Closing this since we are planning to redesign and move the docs app to gatsby.
