### ISSUE TITLE
Adding animations for components

### ISSUE THREAD

**Issue by prasanna1211** [Codebrahma/react-lite-ui#128]
1. ~~Badge: Dynamic entries of the badge count should be animated.~~
2. ~~Card: Expand and collapse should have smooth animation.~~
3. Drawer menu opening and sub menu opening should have animation similar to autocomplete
4. ~~Modal opening and closing should have smooth animation.~~
5. ~~Multi select and select should have same animation as autocomplete~~
6. ~~Snackbar entry and exit should have animation.~~

**Comment by rishichawda** [comment]
@prasanna1211 Drawer doesn't have any menu component. Do we need to add one as a separate component or add it inside the drawer component itself?

**Comment by prasanna1211** [comment]
Mostly it is done. So closing this.
