### ISSUE TITLE
Automating Build + Deployment + version management

### ISSUE THREAD

**Issue by prasanna1211** [Codebrahma/react-lite-ui#13]
Scripts should be created to handle 
1. Build Automation
2. Bundling the root component + Deploying the docs
3. Version management for new builds.
4. Don't allow to merge with master without certain criteria (Test coverage / lint )

Best real world sample would be the scripts in https://github.com/davidchin/react-input-range/blob/master/package.json

**Comment by prasanna1211** [comment]
Automated deployment to netlify.

**Comment by prasanna1211** [comment]
@rishichawda @KRRISH96 Currently only version management is missing. Just use `git tags` to tag the current version of development. Keep 0.X till we release

**Comment by KRRISH96** [comment]
@prasanna1211  `v0.x tag` added from latest development.
