### ISSUE TITLE
AutoComplete suggestion Dropdown

### ISSUE THREAD

**Issue by kaushiknishchay** [Codebrahma/react-lite-ui#136]
The autocomplete dropdown component has a fixed height of '45vh' which looks bad in cases when we have only one suggestion value.

![screenshot 2018-10-26 at 12 06 00 pm](https://user-images.githubusercontent.com/15786884/47548730-85f98e80-d917-11e8-8130-f24dd8b79d24.png)

can be fixed by adding to `id="autocomplete-list"` html tag

```css
height: fit-content;
max-height: 45vh;
```

**Comment by prasanna1211** [comment]
It should be still lower than that. I changed it from 30vh to 45vh for testing animation. In general it should not show beyond 4 items (Also no partial items).

**Comment by kaushiknishchay** [comment]
> It should be still lower than that. I changed it from 30vh to 45vh for testing animation. In general it should not show beyond 4 items (Also no partial items).

updated the max-height value

**Comment by prasanna1211** [comment]
Raised a PR ?

**Comment by kaushiknishchay** [comment]
I haven't made the changes, just reporting the issue.

**Comment by prasanna1211** [comment]
cool. Thanks.
