### ISSUE TITLE
Slider issue on Firefox and IE

### ISSUE THREAD

**Issue by rishichawda** [Codebrahma/react-lite-ui#147]
Problem : Slider not draggable in Mozilla Firefox and on IE it loses focus ( dropped automatically ) when dragged. 

Proposed solution : Rewrite the whole component without native support of draggable from HTML and by using only event listeners on DOM.

Can we fix it without rewriting and changing the whole component - or should we rewrite the component?

**Comment by prasanna1211** [comment]
Preferably ignore default HTML slider and rewrite by implementing a custom one. The more we have HTML elements the more tough it is to customize
