### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by Kameshwaran** [Codebrahma/react-lite-ui#18]
1. Buttons to have box-shadow to make them look like buttons. Currently, they look like a div with text and background
2. Buttons to have effects on hover and click. Make sure that they don't have an outline on `focused` and `active` state.

**Comment by rishichawda** [comment]
Solved in this PR : https://github.com/Codebrahma/react-lite-ui/pull/50 . @prasanna1211 Please check and close this issue.
