### ISSUE TITLE
Minor fixes on usage page.

### ISSUE THREAD

**Issue by rishichawda** [Codebrahma/react-lite-ui#193]
**Describe the issue**

Appropriate spaces and alignment of demo components.

**Screenshots**

![screenshot from 2018-12-06 12-00-06](https://user-images.githubusercontent.com/26366288/49566232-f7cdea80-f94f-11e8-8fc2-a2f328d11026.png)

Could be aligned in a row. There's a lot of unused whitespace on the right side which can be used for proper display.

![screenshot from 2018-12-06 12-00-49](https://user-images.githubusercontent.com/26366288/49566274-1a600380-f950-11e8-9c05-f0da335e7264.png)

Same here. We can have 2 inputs in a row. Will look cleaner. 

![screenshot from 2018-12-06 12-02-24](https://user-images.githubusercontent.com/26366288/49566294-2e0b6a00-f950-11e8-8351-4dff95467116.png)

![screenshot from 2018-12-06 12-02-36](https://user-images.githubusercontent.com/26366288/49566336-4e3b2900-f950-11e8-86d7-e40967397ea7.png)

There should be proper spacing between the buttons and chips. 

![screenshot from 2018-12-06 12-02-50](https://user-images.githubusercontent.com/26366288/49566382-6b6ff780-f950-11e8-9747-b921e38af04a.png)

Other : 

- Table component can be moved a little down so that it has proper spacing with the other components. 
- Snackbar section, Tooltip section and toggle section also need some minor fixes.

Also here. 
**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome.

**Comment by KRRISH96** [comment]
#196
