### ISSUE TITLE
Avatar issues

### ISSUE THREAD

**Issue by prasanna1211** [Codebrahma/react-lite-ui#2]
1. Update docs for avatar
2. `Avatar with Title` should be changed to `Avatar with Alphabets` in the playground of avatar.
3. `title` prop is accepted. But, it has no effect when passed.

**Comment by KRRISH96** [comment]
3. `title` prop is accepted. But, it has no effect when passed.

**Comment by KRRISH96** [comment]
1,2,3 issues fixed.
Ref #32

**Comment by prasanna1211** [comment]
Merged
