### ISSUE TITLE
Switch between Documentation and Usage page of same component.

### ISSUE THREAD

**Issue by KRRISH96** [Codebrahma/react-lite-ui#223]
**Is your feature request related to a problem? Please describe.**

Assume that you are on `Multiselect component documentation` and want to check its `usage`.
Currently, we have to navigate to `Usage` page through `navbar` and select the required component.

**Describe the solution you'd like**

We can have a link at the end of each component to its `usage` or vice versa.

![screenshot from 2018-12-12 15-52-24](https://user-images.githubusercontent.com/22497932/49863286-f86df180-fe25-11e8-9611-145ec4faea89.png)

Now, we can switch to `documentation` or `usage` of a component by one click instead of navbar navigation.

**Comment by rishichawda** [comment]
Seems like a good idea.

**Comment by KRRISH96** [comment]
Done in #224
