### ISSUE TITLE
Badge Issues

### ISSUE THREAD

**Issue by prasanna1211** [Codebrahma/react-lite-ui#3]
1. the badge should have proper padding between components till 2 digits. 
2. the badge width should be based on its content. If the content is more than 2 digits, badge should wrap its content with red background color. Currently the content overflows red background if the digits are more than 2 digits

**Comment by rishichawda** [comment]
Has been fixed in this PR : https://github.com/Codebrahma/react-lite-ui/pull/43 . Please check and merge.
