### ISSUE TITLE
IE issues

### ISSUE THREAD

**Issue by prasanna1211** [Codebrahma/react-lite-ui#38]
Following components have visible issue in IE
badge
checkbox group
chip
menu box shadow
multi select close
navbar

**Comment by rishichawda** [comment]
![menu](https://user-images.githubusercontent.com/26366288/46398410-af593d00-c712-11e8-8cd3-252f66ba2f44.JPG)


Menu shadow is rendered properly on edge.

**Comment by rishichawda** [comment]
![navbar](https://user-images.githubusercontent.com/26366288/46398558-124ad400-c713-11e8-991d-553156d5d21e.JPG)

Navbar search box is also rendered properly.

**Comment by rishichawda** [comment]
![chip](https://user-images.githubusercontent.com/26366288/46398698-6bb30300-c713-11e8-9209-49f88fea016a.JPG)

Chip is also rendering properly and none of the issues in the screenshot below are visible.

<img width="1006" alt="screen shot 2018-10-03 at 1 32 30 pm" src="https://user-images.githubusercontent.com/26366288/46398739-8ab19500-c713-11e8-9cdd-7ae790d06781.png">

**Comment by rishichawda** [comment]
![checkbox](https://user-images.githubusercontent.com/26366288/46398987-35c24e80-c714-11e8-82e8-a3a2c7012036.JPG)

Checkbox also renders properly.

**Comment by rishichawda** [comment]
If issues are resolved, then please merge this PR: https://github.com/Codebrahma/react-lite-ui/pull/56  which applies fixes related to badge and multiselect issue on ie.
