### ISSUE TITLE
Multi select Issue

### ISSUE THREAD

**Issue by prasanna1211** [Codebrahma/react-lite-ui#5]
1. Multi select options display should be scrollable when a row is complete. It shouldn't expand with more components.
2. There should be a border boundary separating the display of selected items and the dropdown fields
3. User should be able to type and filter options. then Pressing enter should select the first filtered option.
4. Add docs.

**Comment by rishichawda** [comment]
@prasanna1211 Please check if the current behavior is correct.

**Comment by rishichawda** [comment]
@prasanna1211 Please check if the current behavior is correct and if all the issues listed above have been solved.
