### ISSUE TITLE
Adding Scripts to package.json for all tasks

### ISSUE THREAD

**Issue by prasanna1211** [Codebrahma/react-lite-ui#94]
Scripts should be added for the following cases
    
    dev: starts dev,
    changelog: changes the log files based on commit,
    lint: "npm run lint:js && npm run lint:scss" // Runs lint,
    prebuild: runs test and deletes previous builds,
    build: creates a new build,
    prepublish: should be same as build, but includes anything before pushing,
    pretest: run lint,
    test: run test
    version: run change log and add changelog.md and update tags

Certain of these can be skipped but the idea remains the same

**Comment by JhonArlex** [comment]
hello, i will work in this issue

**Comment by prasanna1211** [comment]
@JhonArlex Thanks. Are you clear of the task ?

**Comment by JhonArlex** [comment]
What I understand is that I must change the script commands as described in this problem. What I do not understand is for example that start has the command that should go in dev. Should I change the command?

**Comment by prasanna1211** [comment]
I will rephrase with a better understanding.

dev: starts the webpack development of the docs app.
changelog: changes the log files based on commit. We had `conventional changelog` in mind.,
lint: Runs lint for JS and SASS files,
prebuild: runs test and deletes previous builds,
build: creates a new build,
prepublish: should be same as build, but includes anything before pushing,
pretest: run lint,
test: run test (Currently unit tests only)
version: run change log and add changelog.md and update tags if any. Basically it should be easy to update the versions.

All these we had as a thought. We wanted to do automate as much as possible. (It would be okay to skip some of these or add some more)

**Comment by rishichawda** [comment]
resolved in #268
